"""Result containers shared by the Python API and the CLI.

Every result is a frozen dataclass exposing ``to_pandas()``, ``to_json()`` and
``write(prefix)`` so that API and CLI outputs are generated by the same code
path (gate G3, docs/validation.md).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd

from .tree import PhyloNode
from .treeio import to_newick
from .treeio import write_nexus


def node_table(tree: PhyloNode) -> pd.DataFrame:
    """Skeleton table (NodeLabel, NodeId, Des1, Des2) in R3F node order."""
    tips = tree.tips()
    internal = [n for n in tree.walk() if not n.is_tip()]
    rows = []
    for tip in tips:
        rows.append(
            {
                "NodeLabel": tip.label,
                "NodeId": tip.node_id,
                "Des1": "-",
                "Des2": "-",
            }
        )
    for node in internal:
        rows.append(
            {
                "NodeLabel": "-",
                "NodeId": node.node_id,
                "Des1": node.children[0].node_id,
                "Des2": node.children[1].node_id,
            }
        )
    return pd.DataFrame(rows)


def write_report(prefix: str | Path, payload: dict[str, Any]) -> Path:
    """Merge *payload* (keyed by its ``analysis`` field) into ``<prefix>_report.json``.

    Every analysis writing the same prefix contributes its own top-level key
    (``rrf_times``, ``calibrate``, ``corrtest``, ...), so consecutive runs on
    one prefix stay inspectable and reproducible instead of overwriting each
    other.  Legacy files containing a single ``{"analysis": ...}`` block are
    re-keyed transparently on first merge.
    """
    path = Path(f"{prefix}_report.json")
    data: dict[str, Any] = {}
    if path.exists():
        try:
            loaded = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            loaded = None
        if isinstance(loaded, dict):
            if "analysis" in loaded:
                data[str(loaded["analysis"])] = loaded
            else:
                data = loaded
    key = str(payload.get("analysis", "unknown"))
    data[key] = payload
    path.write_text(json.dumps(data, indent=2) + "\n")
    return path


def read_report_block(prefix: str | Path, analysis: str) -> dict[str, Any]:
    """Read one analysis block back from ``<prefix>_report.json``.

    Accepts both the merged format and the legacy single-block format;
    returns ``{}`` when the block is absent.
    """
    path = Path(f"{prefix}_report.json")
    if not path.exists():
        return {}
    try:
        loaded = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(loaded, dict):
        return {}
    if "analysis" in loaded:  # legacy single-block format
        return loaded if loaded.get("analysis") == analysis else {}
    block = loaded.get(analysis)
    return block if isinstance(block, dict) else {}


@dataclass(frozen=True)
class RateResult:
    """Result of :func:`openreltime.rrf_rates`."""

    tree: PhyloNode
    rates: dict[int, float]  # node_id -> relative lineage rate (root = 1.0)
    params: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def to_pandas(self) -> pd.DataFrame:
        df = node_table(self.tree)
        rates = [self.rates.get(int(nid), np.nan) for nid in df["NodeId"]]
        df.insert(4, "Rate", rates)
        return df

    def to_json(self) -> dict[str, Any]:
        return {
            "analysis": "rrf_rates",
            "parameters": self.params,
            "warnings": self.warnings,
            "n_nodes": int(len(self.rates)),
        }

    def write(self, prefix: str | Path, *, r3f_compat: bool = False) -> list[Path]:
        written: list[Path] = []
        suffix = "_RRF_rates" if r3f_compat else "_rates"
        csv_path = Path(f"{prefix}{suffix}.csv")
        self.to_pandas().to_csv(csv_path, index=False)
        written.append(csv_path)
        # tree whose "branch lengths" are the relative rates (R3F semantics,
        # rrf_rates.R line 334)
        rate_tree = self.tree.copy()
        for n in rate_tree.walk():
            if n.is_root():
                continue
            n.blen = self.rates.get(n.node_id, 0.0)
        nwk_path = Path(f"{prefix}{suffix}.nwk")
        nwk_path.write_text(to_newick(rate_tree) + "\n")
        written.append(nwk_path)
        written.append(write_report(prefix, self.to_json()))
        return written


@dataclass(frozen=True)
class TimeResult:
    """Result of :func:`openreltime.rrf_times` / :func:`openreltime.rrf_rates_times`."""

    tree: PhyloNode
    rates: dict[int, float]
    times: dict[int, float]  # node_id -> relative node time (tips = 0)
    n_rate_guarded: int = 0
    params: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def to_pandas(self, with_rate: bool = True) -> pd.DataFrame:
        df = node_table(self.tree)
        times = [self.times.get(int(nid), np.nan) for nid in df["NodeId"]]
        df.insert(4, "Time", times)
        if with_rate:
            rates = [self.rates.get(int(nid), np.nan) for nid in df["NodeId"]]
            df.insert(5, "Rate", rates)
        return df

    def to_json(self) -> dict[str, Any]:
        return {
            "analysis": "rrf_times",
            "parameters": self.params,
            "warnings": self.warnings,
            "n_nodes": int(len(self.times)),
            "n_rate_guarded_nodes": int(self.n_rate_guarded),
        }

    def write(
        self,
        prefix: str | Path,
        *,
        with_rate: bool = False,
        nexus: bool = False,
        r3f_compat: bool = False,
    ) -> list[Path]:
        """Write the node table and the timetree.

        ``nexus=True`` always produces a NEXUS timetree (annotated with
        ``[&rate=...]`` only when ``with_rate`` is set); otherwise a plain
        Newick timetree is written.  This keeps the ``nexus`` flag meaningful
        in every combination.
        """
        written: list[Path] = []
        if r3f_compat:
            csv_name = f"{prefix}_RRF_table.csv" if with_rate else f"{prefix}_RRF_times.csv"
        else:
            csv_name = f"{prefix}_rates_times.csv" if with_rate else f"{prefix}_times.csv"
        csv_path = Path(csv_name)
        self.to_pandas(with_rate=with_rate).to_csv(csv_path, index=False)
        written.append(csv_path)

        tree_name = f"{prefix}_RRF_timetree" if r3f_compat else f"{prefix}_timetree"
        if nexus:
            nexus_path = Path(f"{tree_name}.nexus")
            nexus_path.write_text(
                write_nexus(
                    self.tree,
                    rate_map=self.rates if with_rate else None,
                    time_map=self.times,
                )
            )
            written.append(nexus_path)
        else:
            nwk_path = Path(f"{tree_name}.nwk")
            nwk_path.write_text(to_newick(self.tree, time_map=self.times) + "\n")
            written.append(nwk_path)

        written.append(write_report(prefix, self.to_json()))
        return written


@dataclass(frozen=True)
class CalibrationRecord:
    """One calibration as resolved against the tree (for reporting).

    ``min_bound`` / ``max_bound`` are the bounds the user supplied (the hard
    constraints the CI is truncated at); ``used_min_bound`` / ``used_max_bound``
    are the bounds actually applied to the final point estimate, which differ
    from the user's under ``method="effective"`` (msz236 effective bounds) and
    are what :mod:`openreltime.ci` differentiates.
    """

    target: str
    node_id: int
    min_bound: Optional[float]
    max_bound: Optional[float]
    density: Optional[str] = None
    density_params: dict[str, float] = field(default_factory=dict)
    used_min_bound: Optional[float] = None
    used_max_bound: Optional[float] = None


@dataclass(frozen=True)
class CalibratedResult:
    """Result of :func:`openreltime.calibrate`.

    Two rate vectors are reported because they are different physical
    quantities: ``rates`` are the RRF *relative* lineage rates (msz236 eqs 1-4,
    the same quantity ``rrf_rates``/``rrf_times`` call ``Rate`` and the one the
    CI variance decomposition is stated for), while
    ``implied_rates`` are absolute rates per unit calibrated time, i.e. the bare
    stem length divided by the calibrated duration.  ``implied_rates`` is
    ``NaN`` for lineages whose calibrated duration is not positive.
    """

    tree: PhyloNode
    times: dict[int, float]  # absolute node times (tips = 0)
    rates: dict[int, float]  # RRF relative lineage rates (msz236 r_j)
    time_factor: float
    calibrations: list[CalibrationRecord]
    effective_bounds: Optional[pd.DataFrame] = None
    empirical_ci: Optional[pd.DataFrame] = None
    params: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    implied_rates: dict[int, float] = field(default_factory=dict)

    def to_pandas(self) -> pd.DataFrame:
        df = node_table(self.tree)
        times = [self.times.get(int(nid), np.nan) for nid in df["NodeId"]]
        rrf = [self.rates.get(int(nid), np.nan) for nid in df["NodeId"]]
        implied = [self.implied_rates.get(int(nid), np.nan) for nid in df["NodeId"]]
        df.insert(4, "Time", times)
        df.insert(5, "RRFRate", rrf)
        df.insert(6, "ImpliedRate", implied)
        return df

    def to_json(self) -> dict[str, Any]:
        return {
            "analysis": "calibrate",
            "parameters": self.params,
            "warnings": self.warnings,
            "time_factor": self.time_factor,
            "rate_definitions": {
                "RRFRate": self.params.get(
                    "rate_definition", "RRF relative lineage rates (msz236 eqs 1-4)"
                ),
                "ImpliedRate": self.params.get(
                    "implied_rate_definition",
                    "stem branch length / (parent age - node age)",
                ),
            },
            "calibrations": [
                {
                    "target": c.target,
                    "node_id": c.node_id,
                    "min_bound": c.min_bound,
                    "max_bound": c.max_bound,
                    "density": c.density,
                    "density_params": c.density_params,
                    "used_min_bound": c.used_min_bound,
                    "used_max_bound": c.used_max_bound,
                }
                for c in self.calibrations
            ],
        }

    def write(self, prefix: str | Path, *, nexus: bool = True) -> list[Path]:
        """Write the calibrated table, the absolute-time tree and diagnostics.

        The Newick timetree is always written; ``nexus=True`` additionally
        writes a ``[&rate=...]``-annotated NEXUS version.
        """
        written: list[Path] = []
        csv_path = Path(f"{prefix}_calibrated.csv")
        self.to_pandas().to_csv(csv_path, index=False)
        written.append(csv_path)
        nwk_path = Path(f"{prefix}_calibrated.nwk")
        nwk_path.write_text(to_newick(self.tree, time_map=self.times) + "\n")
        written.append(nwk_path)
        if nexus:
            nexus_path = Path(f"{prefix}_calibrated.nexus")
            nexus_path.write_text(
                write_nexus(self.tree, rate_map=self.rates, time_map=self.times)
            )
            written.append(nexus_path)
        if self.effective_bounds is not None:
            eb_path = Path(f"{prefix}_effective_bounds.csv")
            self.effective_bounds.to_csv(eb_path, index=False)
            written.append(eb_path)
        written.append(write_report(prefix, self.to_json()))
        return written


@dataclass(frozen=True)
class CIResult:
    """Result of :func:`openreltime.confidence_interval`.

    ``table`` carries one row per internal node: ``node_id, label, time, se,
    lower, upper, width, se_reliable, notes``.  ``se_reliable`` is ``False``
    wherever the interval does not come from the branch-variance decomposition
    of msz236 eq (7) - a node whose age is pinned at a hard calibration bound,
    or a node with no computable variance - and ``notes`` says which.
    """

    table: pd.DataFrame
    level: float
    method: str
    params: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        flagged = 0
        if "se_reliable" in self.table.columns:
            flagged = int((~self.table["se_reliable"].astype(bool)).sum())
        return {
            "analysis": "confidence_interval",
            "level": self.level,
            "method": self.method,
            "parameters": self.params,
            "n_nodes": int(len(self.table)),
            "n_nodes_se_not_reliable": flagged,
        }

    def write(self, prefix: str | Path) -> list[Path]:
        written: list[Path] = []
        csv_path = Path(f"{prefix}_ci.csv")
        self.table.to_csv(csv_path, index=False)
        written.append(csv_path)
        written.append(write_report(prefix, self.to_json()))
        return written


@dataclass(frozen=True)
class CorrTestResult:
    """Result of :func:`openreltime.corrtest`."""

    rho_s: float
    rho_ad: float
    rho_ad_1_decay: float
    rho_ad_2_decay: float
    score: float
    p_band: str
    anchor: Optional[dict[str, float]] = None
    params: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        return {
            "analysis": "corrtest",
            "rho_s": self.rho_s,
            "rho_ad": self.rho_ad,
            "rho_ad_1_decay": self.rho_ad_1_decay,
            "rho_ad_2_decay": self.rho_ad_2_decay,
            "CorrScore": self.score,
            "P_value": self.p_band,
            "anchor": self.anchor,
            "parameters": self.params,
        }

    def write(self, prefix: str | Path) -> list[Path]:
        written: list[Path] = []
        txt_path = Path(f"{prefix}_corrtest.txt")
        lines = [f"score = {self.score:.5g}", self.p_band]
        if self.anchor:
            lines.append(f"mean of rates = {self.anchor['mean.rate']:.5g}")
            lines.append(f"SD of rates = {self.anchor['sd.rate']:.5g}")
        txt_path.write_text("\n".join(lines) + "\n")
        written.append(txt_path)
        written.append(write_report(prefix, self.to_json()))
        return written


@dataclass(frozen=True)
class DDBDResult:
    """Result of :func:`openreltime.ddbd`."""

    birth_rate: float
    death_rate: float
    sampling_frac: float
    scale_factor: float
    anchor_node: Optional[int] = None
    anchor_time: Optional[float] = None
    params: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        return {
            "analysis": "ddbd",
            "birth.rate": self.birth_rate,
            "death.rate": self.death_rate,
            "sampling.frac": self.sampling_frac,
            "scale.factor": self.scale_factor,
            "anchor.node": self.anchor_node,
            "anchor.time": self.anchor_time,
            "parameters": self.params,
        }

    def write(self, prefix: str | Path) -> list[Path]:
        written: list[Path] = []
        txt_path = Path(f"{prefix}_ddbd.txt")
        txt_path.write_text(
            "birth.rate\tdeath.rate\tsampling.frac\n"
            f"{self.birth_rate}\t{self.death_rate}\t{self.sampling_frac}\n"
        )
        written.append(txt_path)
        written.append(write_report(prefix, self.to_json()))
        return written
